import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import BackButton from '../components/BackButton'; // Import the BackButton component

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// Metadata can now be used because we're in a server component
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* BackButton is now globally available */}
        <BackButton /> {/* Add the back button to the layout */}

        {/* Render children (pages) here */}
        {children}
      </body>
    </html>
  );
}
